upload-folder: uploads

spring:
  datasource:
    url: jdbc:sqlserver://{DATABASE SERVER};databaseName={DATABASE NAME}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: {DATABASE USER}
    password: {DATABASE PASSWORD}
    initialization-mode: never
    platform: dev
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
