upload-folder: uploads

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MSSQLServer;MODE=MSSQLServer;INIT=CREATE SCHEMA IF NOT EXISTS PREDICTED_GRADE
    driverClassName: org.h2.Driver
    username: sa
    password:
    
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

